name: medrax
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.0=py310h06a4308_0
  - python=3.10.16=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==1.6.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - albucore==0.0.23
      - albumentations==2.0.5
      - annotated-types==0.7.0
      - anthropic==0.49.0
      - anyio==4.9.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==4.0.3
      - attrs==25.3.0
      - babel==2.17.0
      - backoff==2.2.1
      - beautifulsoup4==4.13.3
      - bitsandbytes==0.45.4
      - bleach==6.2.0
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - comm==0.2.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - debugpy==1.8.13
      - decorator==5.2.1
      - defusedxml==0.7.1
      - diffusers==0.32.2
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - einops-exts==0.0.4
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastapi==0.115.12
      - fastjsonschema==2.21.1
      - ffmpy==0.5.0
      - filelock==3.18.0
      - fonttools==4.57.0
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2025.3.2
      - gdcm==1.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gradio==5.23.3
      - gradio-client==1.8.0
      - greenlet==3.1.1
      - groovy==0.1.2
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==0.30.1
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - iniconfig==2.1.0
      - ipykernel==6.29.5
      - ipython==8.34.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.9.0
      - joblib==1.4.2
      - json5==0.12.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - langchain==0.3.23
      - langchain-anthropic==0.3.10
      - langchain-community==0.3.21
      - langchain-core==0.3.51
      - langchain-openai==0.3.12
      - langchain-text-splitters==0.3.8
      - langgraph==0.3.25
      - langgraph-checkpoint==2.0.24
      - langgraph-prebuilt==0.1.8
      - langgraph-sdk==0.1.61
      - langsmith==0.3.24
      - latex2mathml==3.77.0
      - lazy-loader==0.4
      - markdown-it-py==3.0.0
      - markdown2==2.5.3
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - -e .
      - mistune==3.1.3
      - mpmath==1.3.0
      - multidict==6.3.2
      - mypy-extensions==1.0.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - notebook==7.3.3
      - notebook-shim==0.2.4
      - numpy==2.2.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.70.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - orjson==3.10.16
      - ormsgpack==1.9.1
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - peft==0.15.1
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.7
      - pluggy==1.5.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - propcache==0.3.1
      - protobuf==5.29.4
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==19.0.1
      - pycparser==2.22
      - pydantic==2.11.2
      - pydantic-core==2.33.1
      - pydantic-settings==2.8.1
      - pydicom==3.0.1
      - pydub==0.25.1
      - pygments==2.19.1
      - pylibjpeg==2.0.1
      - pyparsing==3.2.3
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.0.0
      - rpds-py==0.24.0
      - ruff==0.11.4
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentence-transformers==4.0.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.26.1
      - setproctitle==1.3.5
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - simsimd==6.2.1
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==2.0.40
      - stack-data==0.6.3
      - starlette==0.46.1
      - stringzilla==3.12.3
      - svgwrite==1.4.3
      - sympy==1.13.1
      - tenacity==9.1.2
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tifffile==2025.3.30
      - tiktoken==0.9.0
      - timm==1.0.15
      - tinycss2==1.4.0
      - tokenizers==0.20.3
      - tomli==2.2.1
      - tomlkit==0.13.2
      - torch==2.6.0
      - torchvision==0.21.0
      - torchxrayvision==1.3.3
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.46.0.dev0
      - triton==3.2.0
      - typer==0.15.2
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.13.1
      - typing-inspect==0.9.0
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - wandb==0.19.9
      - wavedrom==2.0.3.post3
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==15.0.1
      - widgetsnbextension==4.0.13
      - xxhash==3.5.0
      - yarl==1.19.0
      - zipp==3.21.0
      - zstandard==0.23.0
